on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Run HTML Linter
        uses: github/super-linter@v4
        continue-on-error: true
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Check for Broken Links
        uses: lycheeverse/lychee-action@v2
        with:
          fail: true
          args: >-
            --verbose https://dlitov.github.io/
            --exclude https://dlitov.github.io/favicon.ico
            --exclude https://formspree.io/f/xpwdvnno
            --exclude https://www.linkedin.com/in/dimitar-litov-442904139/
            --exclude https://facebook.dlocal.com/
            --exclude https://facebook.payulatam.com/
            --exclude https://integration-facebook.payu.in/
            --exclude https://buy2.boku.com/
            --exclude http://ns.adobe.com/xap/1.0/
            --exclude http://ns.adobe.com/xap/1.0/mm/
            --exclude http://ns.adobe.com/photoshop/1.0/
            --exclude http://ns.adobe.com/camera-raw-settings/1.0/
            --exclude http://ns.adobe.com/exif/1.0/aux/
            --exclude http://ns.adobe.com/xap/1.0/sType/ResourceEvent#
            --exclude http://ns.adobe.com/xap/1.0/sType/ResourceRef#
            --exclude http://purl.org/dc/elements/1.1/
