on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-html:
    name: HTML Linting with Super-Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Super-Linter
        uses: github/super-linter@v6
        env:
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_HTML: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  check-links:
    name: Link Check with Lychee
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install lychee
        run: |
          curl -sSfL https://github.com/lycheeverse/lychee/releases/latest/download/lychee-x86_64-unknown-linux-gnu.tar.gz | tar xz
          sudo mv lychee /usr/local/bin/

      - name: Check for broken links
        run: |
          lychee --verbose --no-progress "**/*.html"
