on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Run HTML Linter
        uses: github/super-linter@v4
        continue-on-error: true
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Check for Broken Links
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose https://dlitov.github.io/ --exclude "https://www.facebook.com/dimitar.litov https://www.linkedin.com/in/dimitar-litov-442904139/ https://dlitov.github.io/images/project.jpg https://dlitov.github.io/favicon.ico https://raw.githubusercontent.com/DLitov/DLitov.github.io/main/CV-Dimitar%20Litov-new.doc"
          fail: true
