on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Run HTML Linter
        uses: github/super-linter@v4
        continue-on-error: true
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Check for Broken Links
        uses: lycheeverse/lychee-action@v2
        with:
          fail: true
          args: --verbose https://dlitov.github.io/ --exclude "https://dlitov.github.io/favicon.ico https://formspree.io/f/xpwdvnno https://www.linkedin.com/in/dimitar-litov-442904139/ https://www.facebook.com/dimitar.litov https://dlitov.github.io/images/project.jpg https://raw.githubusercontent.com/DLitov/DLitov.github.io/main/CV-Dimitar%20Litov-new.doc"
